{"name": "Ошибка аутентификации с неверными данными", "status": "passed", "description": "Проверяем невозможность входа в систему при использовании несуществующего логина или неправильного пароля. Код ответа: 404.", "parameters": [{"name": "nonexistent_credentials", "value": "{'login': 'Service543', 'password': 'WrongPass123'}"}], "start": 1737560056615, "stop": 1737560057703, "uuid": "f3ec89a2-4ced-4440-8e29-ad440676c51b", "historyId": "ff4ea9634d3166bb0effac93cf50a48a", "testCaseId": "199be2f2af7455b14ed4795a4ee970da", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_nonexistent_data_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-T8QAB49"}, {"name": "thread", "value": "24840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}