{"name": "Ошибка аутентификации с неверными данными", "status": "passed", "description": "Проверяем невозможность входа в систему при использовании несуществующего логина или неправильного пароля. Код ответа: 404.", "parameters": [{"name": "nonexistent_credentials", "value": "{'login': 'Situation221', 'password': '^!B+dRkC%m7g'}"}], "start": 1737560055742, "stop": 1737560056611, "uuid": "0d2611fa-2e27-4c1c-a5da-293c7292d877", "historyId": "56c44577ecc6011ae06c3fc30e7d34b0", "testCaseId": "199be2f2af7455b14ed4795a4ee970da", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_nonexistent_data_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-T8QAB49"}, {"name": "thread", "value": "24840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}